#
# Autogenerated by Thrift Compiler (0.13.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

class Resultado; end

class Resultado
  include ::Thrift::Struct, ::Thrift::Struct_Union
  RESULTADO = 1
  MENSAJEERROR = 2

  FIELDS = {
    RESULTADO => {:type => ::Thrift::Types::DOUBLE, :name => 'resultado'},
    MENSAJEERROR => {:type => ::Thrift::Types::STRING, :name => 'mensajeError'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

